name: lua

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
         luaVersion: ["5.1.5", "5.2.4", "luajit"]
    
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Install
      run: |
        sudo apt-get install libssl1.0-dev
        luarocks install --server=http://luarocks.org/dev openssl
        luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
        luarocks install busted
        luarocks install rapidjson 0.7.1
        luarocks install luacrypto 0.3.2-2
        luarocks install date 2.1.2-1
    - name: Test
      run: busted spec